export const GET_PRODUCTS = "@app/GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "@app/GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "@app/GET_PRODUCTS_FAILED";
export const GET_CAMPAIGN = "@app/GET_CAMPAIGN";
export const GET_CAMPAIGN_SUCCESS = "@app/GET_CAMPAIGN_SUCCESS";
export const GET_CAMPAIGN_FAILED = "@app/GET_CAMPAIGN_FAILED";
