export const GET_PROFILE_INFO = "@profile/GET_PROFILE_INFO";
export const GET_PROFILE_INFO_SUCCESS = "@profile/GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_FAILED = "@profile/GET_PROFILE_INFO_FAILED";

export const POST_UPDATE_PROFILE = "@profile/POST_UPDATE_PROFILE";
export const POST_UPDATE_PROFILE_SUCCESS =
  "@profile/POST_UPDATE_PROFILE_SUCCESS";
export const POST_UPDATE_PROFILE_FAILED = "@profile/POST_UPDATE_PROFILE_FAILED";

export const POST_UPDATE_SHIPPING_ADDRESS =
  "@profile/POST_UPDATE_SHIPPING_ADDRESS";
export const POST_UPDATE_SHIPPING_ADDRESS_SUCCESS =
  "@profile/POST_UPDATE_SHIPPING_ADDRESS_SUCCESS";
export const POST_UPDATE_SHIPPING_ADDRESS_FAILED =
  "@profile/POST_UPDATE_SHIPPING_ADDRESS_FAILED";

export const CLEAR_USER_PROFILE = "@profile/CLEAR_USER_PROFILE";
